version: '3.8'

services:

  node:

    container_name: nodeapp

    build:
      context: .
      dockerfile: Dockerfile
      
    ports:
      - 3000:3000

    depends_on:
      - mongo


  mongo:

    image: mongo:4.2-bionic
    container_name: mongodb

    restart: always

    expose:
      - 27017

    volumes:
      - ./mongoData:/data/db

volumes:
  mongoData:
