version: '3.8'

services:
  pyapp:

    container_name: pyapp

    build:
      context: .
      dockerfile: Dockerfile
      
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    
    volumes:
      - ./code:/src:ro
    
    ports:
      - 8000:8000

    depends_on:
      - postgresdb
      - redisdb

    networks:
      custom-network:
        ipv4_address: 172.24.2.3

  postgresdb:
    
    container_name: psqldb

    image: postgres:13-alpine
    
    volumes:
      - psql_data:/var/lib/postgresql/data:rw
    
    expose:
      - 5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    networks:
      custom-network:
        ipv4_address: 172.24.2.4
        # IP for other instance of Postgres DB
        # ipv4_address: 172.24.2.5


  redisdb:

    container_name: redisdb

    image: redis:alpine3.16

    volumes:
      - redis_data:/data:rw

    expose:
      - 6379

    networks:
      custom-network:
        ipv4_address: 172.24.2.6

volumes:
  psql_data:
  redis_data:

networks:
  custom-network: 
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.2.0/16
         gateway: 172.24.2.1