version: '3.8'

services:
  pyapp:

    container_name: pyapp

    build:
      context: .
      dockerfile: Dockerfile
      
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    
    volumes:
      - ./code:/src
    
    ports:
      - 8000:8000

    depends_on:
      - postgresdb
      - redis

  postgresdb:
    
    container_name: psqldb

    image: postgres:13-alpine
    
    volumes:
      - psql_data:/var/lib/postgresql/data
    
    expose:
      - 5432

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redisdb:

    container_name: redisdb

    image: redis:alpine3.16

    volumes:
      - redis_data:/data

volumes:
  psql_data:
  redis_data:
